# Generated by Django 4.1.5 on 2023-02-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_app', '0005_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
