# Generated by Django 4.1.5 on 2023-02-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_app', '0006_watchlist_avg_rating_watchlist_number_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='website',
            field=models.URLField(max_length=100),
        ),
    ]
